#!/bin/bash

# make sure you do the command
# chmod u+x runScript
# run with the command
# nohup ./runScript  &
# It will put its output into a file named nohup.out.

#./part1-t1 is the executable compiled for 1 thread
#./part1-t2 is the executable compiled for 2 threads
#./part1-t4 is the executable compiled for 4 threads, etc.

# These jobs will run one after the other in series, putting the
# information sent to stdout/stderr into the out.* files so you can
# get the execution time results from those files.

echo -e "MIT WORDLIST=============================================================\n\n" >> out.test 2>&1

echo -e "SEQUENTIAL-----------------------------------------------------------\n\n" >> out.test 2>&1

./bloom-seq testfiles/MITwordlist testfiles/MITwordlist >> out.test 2>&1
./bloom-seq testfiles/MITwordlist testfiles/MITwordlist >> out.test 2>&1
./bloom-seq testfiles/MITwordlist testfiles/MITwordlist >> out.test 2>&1
./bloom-seq testfiles/MITwordlist testfiles/MITwordlist >> out.test 2>&1
./bloom-seq testfiles/MITwordlist testfiles/MITwordlist >> out.test 2>&1

echo -e "CUDA-----------------------------------------------------------\n\n" >> out.test 2>&1

./bloom-cuda testfiles/MITwordlist testfiles/MITwordlist >> out.test 2>&1
./bloom-cuda testfiles/MITwordlist testfiles/MITwordlist >> out.test 2>&1
./bloom-cuda testfiles/MITwordlist testfiles/MITwordlist >> out.test 2>&1
./bloom-cuda testfiles/MITwordlist testfiles/MITwordlist >> out.test 2>&1
./bloom-cuda testfiles/MITwordlist testfiles/MITwordlist >> out.test 2>&1

echo -e "\nBig WORDLIST=============================================================\n\n" >> out.test 2>&1

echo -e "SEQUENTIAL-----------------------------------------------------------\n\n" >> out.test 2>&1

./bloom-seq testfiles/words.txt testfiles/MITwordlist >> out.test 2>&1
./bloom-seq testfiles/words.txt testfiles/MITwordlist >> out.test 2>&1
./bloom-seq testfiles/words.txt testfiles/MITwordlist >> out.test 2>&1
./bloom-seq testfiles/words.txt testfiles/MITwordlist >> out.test 2>&1
./bloom-seq testfiles/words.txt testfiles/MITwordlist >> out.test 2>&1

echo -e "CUDA-----------------------------------------------------------\n\n" >> out.test 2>&1

./bloom-cuda testfiles/words.txt testfiles/MITwordlist >> out.test 2>&1
./bloom-cuda testfiles/words.txt testfiles/MITwordlist >> out.test 2>&1
./bloom-cuda testfiles/words.txt testfiles/MITwordlist >> out.test 2>&1
./bloom-cuda testfiles/words.txt testfiles/MITwordlist >> out.test 2>&1
./bloom-cuda testfiles/words.txt testfiles/MITwordlist >> out.test 2>&1
